import { AlertOctagon, ArrowRightLeft, Pause, Play, RefreshCw, RotateCcw, Search, ServerCog, TriangleAlert } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Badge, ConnectionBadge, Drawer, EmptyState, InfoBanner, ProtocolBadge, SectionHeader, formatDate } from '../components/UI'
import { canRole, useHealthConnectStore } from '../stores/useHealthConnectStore'

export function InterfacesPage(){
  const {interfaces,systems,currentRole,pauseInterface,createInterfaceError,restoreInterface,simulateSync}=useHealthConnectStore()
  const [query,setQuery]=useState(''); const [selectedId,setSelectedId]=useState<string>()
  const selected=interfaces.find(i=>i.id===selectedId); const system=systems.find(s=>s.id===selected?.sourceSystemId)
  const visible=useMemo(()=>interfaces.filter(i=>!query||i.name.toLowerCase().includes(query.toLowerCase())||systems.find(s=>s.id===i.sourceSystemId)?.name.toLowerCase().includes(query.toLowerCase())),[interfaces,systems,query])
  const canManage=canRole(currentRole, 'interface-manage')
  return <div><div className="page-hero"><div><div className="eyebrow">DATA EXCHANGE</div><h1>Interfaces</h1><p>Monitor synthetic FHIR, HL7 v2, DICOM, REST and event-stream connections and simulate realistic integration failures.</p></div><div className="search-inline"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search interfaces..."/></div></div>{!canManage&&<InfoBanner kind="warning" title="Read-only for current role">Switch to Integration Engineer or Administrator to pause, degrade, restore or sync interfaces.</InfoBanner>}
    <section className="panel"><SectionHeader title="Interface health" subtitle="Buttons change shared state and downstream Patient 360 freshness."/>{visible.length===0?<EmptyState title="No interfaces match" detail="Change the search query to inspect another synthetic interface."/>:<div className="table-scroll"><table><thead><tr><th>Interface</th><th>Source</th><th>Protocol</th><th>Direction</th><th>Last message</th><th>Messages/hr</th><th>Errors</th><th>Status</th><th></th></tr></thead><tbody>{visible.map(i=>{const s=systems.find(x=>x.id===i.sourceSystemId);return <tr key={i.id}><td><strong>{i.name}</strong><small>{i.endpointLabel}</small></td><td>{s?.organization}</td><td><ProtocolBadge protocol={i.protocol}/></td><td><span className="inline-icon"><ArrowRightLeft size={14}/>{i.direction}</span></td><td>{formatDate(i.lastMessage)}</td><td>{i.messagesPerHour.toLocaleString()}</td><td>{i.errors}</td><td><ConnectionBadge status={i.status}/></td><td><button className="secondary-button compact" onClick={()=>setSelectedId(i.id)}>Manage</button></td></tr>})}</tbody></table></div>}</section>

    <Drawer open={Boolean(selected)} title={selected?.name??'Interface'} subtitle={system?.organization} onClose={()=>setSelectedId(undefined)} wide>
      {selected&&system&&<><div className="detail-kpis"><div><span>Status</span><ConnectionBadge status={selected.status}/></div><div><span>Protocol</span><ProtocolBadge protocol={selected.protocol}/></div><div><span>Errors</span><strong>{selected.errors}</strong></div><div><span>Messages/hr</span><strong>{selected.messagesPerHour.toLocaleString()}</strong></div></div>
      <div className="integration-detail-grid"><section><h3>Connection</h3><dl className="key-value"><dt>Source system</dt><dd>{system.name}</dd><dt>Endpoint</dt><dd>{selected.endpointLabel}</dd><dt>Direction</dt><dd>{selected.direction}</dd><dt>Last message</dt><dd>{formatDate(selected.lastMessage)}</dd></dl></section><section><h3>Data domains</h3><div className="tag-list">{system.dataDomains.map(d=><Badge key={d}>{d}</Badge>)}</div><p className="muted">This is a simulated connection. No live healthcare endpoint is contacted.</p></section></div>
      {selected.status==='Degraded'&&<InfoBanner kind="critical" title="Downstream freshness affected">Records from this source are marked Delayed in Patient 360 until the interface is restored and a synthetic sync is completed.</InfoBanner>}
      <div className="action-grid"><button className="secondary-button" disabled={!canManage||!['Connected','Delayed'].includes(selected.status)} onClick={()=>pauseInterface(selected.id)}><Pause size={16}/>Pause feed</button><button className="danger-button" disabled={!canManage||!['Connected','Delayed'].includes(selected.status)} onClick={()=>createInterfaceError(selected.id)}><AlertOctagon size={16}/>Create demo error</button><button className="secondary-button" disabled={!canManage||selected.status==='Connected'} onClick={()=>restoreInterface(selected.id)}><RotateCcw size={16}/>Restore connection</button><button className="primary-button" disabled={!canManage||selected.status!=='Connected'} onClick={()=>simulateSync(selected.id)}><RefreshCw size={16}/>Simulate sync</button></div>
      <div className="demo-note"><TriangleAlert size={18}/><div><strong>Recommended demo</strong><span>For Metro Diagnostics ORU: Create Demo Error → open Emily Patient 360 to see delayed lab warning → Restore Connection → Simulate Sync → verify a new lab record and Current freshness.</span></div></div></>}
    </Drawer>
  </div>
}
